spring.application.name=mindtrack-backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/mindtrack_db
spring.datasource.username=postgres
spring.datasource.password=411070
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=9a76384962b8a734e56c82d92d47384a51e62c72b8d93e8271a36b48d2f19a0a
jwt.expiration=604800000
